import "~/styles/globals.css";

import type { Metadata } from "next";
import { Manrope, Poppins } from "next/font/google";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const poppins = Poppins({
	weight: ["400", "500", "600"],
	subsets: ["latin"],
	variable: "--font-poppins-sans",
});

const manrope = Manrope({
	subsets: ["latin"],
	variable: "--font-manrope-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${manrope.variable} ${poppins.variable}`}>
			<body className="max-w-[1920px]">{children}</body>
		</html>
	);
}
